"use strict";(self.webpackChunkdocs=self.webpackChunkdocs||[]).push([[983],{4911:(e,r,t)=>{t.r(r),t.d(r,{assets:()=>c,contentTitle:()=>a,default:()=>h,frontMatter:()=>i,metadata:()=>n,toc:()=>l});const n=JSON.parse('{"id":"error-boundary-usage","title":"Sentry/React Error Boundary","description":"Explains how to use sentry-testkit with the Sentry/React Error Boundary","source":"@site/docs/error-boundary-usage.md","sourceDirName":".","slug":"/error-boundary-usage","permalink":"/sentry-testkit/docs/error-boundary-usage","draft":false,"unlisted":false,"editUrl":"https://github.com/zivl/sentry-testkit/blob/master/website/docs/docs/error-boundary-usage.md","tags":[],"version":"current","sidebarPosition":3,"frontMatter":{"title":"Sentry/React Error Boundary","description":"Explains how to use sentry-testkit with the Sentry/React Error Boundary","sidebar_position":3},"sidebar":"tutorialSidebar","previous":{"title":"API Reference","permalink":"/sentry-testkit/docs/api/"},"next":{"title":"Network Interception","permalink":"/sentry-testkit/docs/network-interception"}}');var o=t(4848),s=t(8453);const i={title:"Sentry/React Error Boundary",description:"Explains how to use sentry-testkit with the Sentry/React Error Boundary",sidebar_position:3},a="Usage with <Sentry.ErrorBoundary>",c={},l=[{value:"3 Errors are sent to Sentry",id:"3-errors-are-sent-to-sentry",level:2},{value:"Test Code Example",id:"test-code-example",level:3},{value:"What Else Can Be Done About It?",id:"what-else-can-be-done-about-it",level:2}];function d(e){const r={a:"a",admonition:"admonition",code:"code",h1:"h1",h2:"h2",h3:"h3",header:"header",li:"li",ol:"ol",p:"p",pre:"pre",...(0,s.R)(),...e.components};return(0,o.jsxs)(o.Fragment,{children:[(0,o.jsx)(r.header,{children:(0,o.jsxs)(r.h1,{id:"usage-with-sentryerrorboundary",children:["Usage with ",(0,o.jsx)(r.code,{children:"<Sentry.ErrorBoundary>"})]})}),"\n",(0,o.jsxs)(r.p,{children:["The ",(0,o.jsx)(r.code,{children:"@sentry/react"})," library exposes a ",(0,o.jsx)(r.code,{children:"<Sentry.ErrorBoundary>"})," React component that can be used to catch errors in React components, similar to the ",(0,o.jsx)(r.code,{children:"componentDidCatch"})," lifecycle method."]}),"\n",(0,o.jsxs)(r.p,{children:["However, the ",(0,o.jsx)(r.code,{children:"<Sentry.ErrorBoundary>"})," component causes Sentry to send multiple events due to the way it works under the hood. This is because it catches errors in the ",(0,o.jsx)(r.code,{children:"componentDidCatch"})," lifecycle method, and then re-throws them, which causes Sentry to send another event. This is not a problem in production, but it can be a problem when testing."]}),"\n",(0,o.jsx)(r.h2,{id:"3-errors-are-sent-to-sentry",children:"3 Errors are sent to Sentry"}),"\n",(0,o.jsxs)(r.p,{children:["When using ",(0,o.jsx)(r.code,{children:"sentry-testkit"})," to test Sentry reports, the ",(0,o.jsx)(r.code,{children:"testkit.reports()"})," call will return the following 3 total errors, as explained in ",(0,o.jsx)(r.a,{href:"https://github.com/getsentry/sentry-javascript/issues/9514#issuecomment-1805723611",children:"Sentry's issue #9514"}),":"]}),"\n",(0,o.jsxs)(r.ol,{children:["\n",(0,o.jsx)(r.li,{children:"The original error that is captured by the error boundary"}),"\n",(0,o.jsx)(r.li,{children:"The original error captured by global event listener. This only occurs in in dev mode, because error boundaries rethrow the errors that they catch and those errors bubble up to the global event listener where it is captured again."}),"\n",(0,o.jsxs)(r.li,{children:["A synthetic react error boundary error that is generated by the sentry react sdk and attached to an error. This synthetic error is not captured as a standalone sentry event, but instead is included as part of the sentry event sent for the original error sent by the error boundary. See ",(0,o.jsx)(r.a,{href:"https://docs.sentry.io/platforms/javascript/guides/react/features/error-boundary/#linked-errors",children:"Linked Errors"})," for more details."]}),"\n"]}),"\n",(0,o.jsxs)(r.p,{children:["Internally, ",(0,o.jsx)(r.code,{children:"sentry-testkit"})," uses the ",(0,o.jsx)(r.code,{children:"testkit.reports()"})," call to find the report for the original error, so it will return the first error in the list above. This is the error that you should use to test your application."]}),"\n",(0,o.jsx)(r.admonition,{title:"2 Sentry events are being sent",type:"info",children:(0,o.jsxs)(r.p,{children:["Event A -> original error (1) + synthetic error boundary error (3)",(0,o.jsx)("br",{}),"\nEvent B -> original error from global handlers (2)"]})}),"\n",(0,o.jsx)(r.h3,{id:"test-code-example",children:"Test Code Example"}),"\n",(0,o.jsx)(r.pre,{children:(0,o.jsx)(r.code,{className:"language-javascript",children:"import React from 'react'\nimport '@testing-library/jest-dom'\nimport { render } from '@testing-library/react'\nimport * as Sentry from '@sentry/react'\nimport sentryTestkit from 'sentry-testkit'\n\nconst { testkit, sentryTransport } = sentryTestkit()\n\nconst ThrowError = () => {\n  // eslint-disable-next-line\n  throw Error('test error')\n}\n\ndescribe('Inside ErrorBoundary', () => {\n  const consoleError = console.error\n  beforeAll(() => {\n    console.error = jest.fn()\n    Sentry.init({\n      dsn: 'https://acacaeaccacacacabcaacdacdacadaca@sentry.io/000001',\n      transport: sentryTransport,\n    })\n  })\n  afterAll(() => {\n    console.error = consoleError\n  })\n\n  test('should render fallback component and captureException when error is thrown', async () => {\n    expect(testkit.reports()).toHaveLength(0)\n    render(\n      <Sentry.ErrorBoundary fallback={<div>some error</div>}>\n        <ThrowError />\n      </Sentry.ErrorBoundary>\n    )\n    expect(testkit.reports()).toHaveLength(3)\n  })\n})\n"})}),"\n",(0,o.jsx)(r.h2,{id:"what-else-can-be-done-about-it",children:"What Else Can Be Done About It?"}),"\n",(0,o.jsx)(r.p,{children:"You can alway customize it through Sentry's Integrations mechanism."}),"\n",(0,o.jsxs)(r.p,{children:["For example, you can disable the ",(0,o.jsx)(r.code,{children:"GlobalHandler"})," Integration by doing the following:"]}),"\n",(0,o.jsx)(r.pre,{children:(0,o.jsx)(r.code,{className:"language-javascript",children:"import * as Sentry from '@sentry/react'\nimport { Integrations } from '@sentry/tracing'\n\nSentry.init({\n  // ...\n  integrations: function (integrations) {\n    return integrations.filter(function (integration) {\n      return integration.name !== \"GlobalHandlers\";\n    });\n  },\n});\n\n"})}),"\n",(0,o.jsxs)(r.p,{children:["You can also take a look on the ",(0,o.jsx)(r.code,{children:"CaptureConsole"})," Integration, which is responsible for capturing console errors. You can disable it by doing the following:"]}),"\n",(0,o.jsx)(r.pre,{children:(0,o.jsx)(r.code,{className:"language-javascript",children:"import * as Sentry from '@sentry/react'\nimport { Integrations } from '@sentry/tracing'\n\nSentry.init({\n  // ...\n  integrations: function (integrations) {\n    return integrations.filter(function (integration) {\n      return integration.name !== \"CaptureConsole\";\n    });\n  },\n});\n"})}),"\n",(0,o.jsx)(r.admonition,{type:"info",children:(0,o.jsxs)(r.p,{children:["Find more information about Sentry's Integrations ",(0,o.jsx)(r.a,{href:"https://docs.sentry.io/platforms/javascript/configuration/integrations",children:"here"}),"."]})})]})}function h(e={}){const{wrapper:r}={...(0,s.R)(),...e.components};return r?(0,o.jsx)(r,{...e,children:(0,o.jsx)(d,{...e})}):d(e)}},8453:(e,r,t)=>{t.d(r,{R:()=>i,x:()=>a});var n=t(6540);const o={},s=n.createContext(o);function i(e){const r=n.useContext(s);return n.useMemo((function(){return"function"==typeof e?e(r):{...r,...e}}),[r,e])}function a(e){let r;return r=e.disableParentContext?"function"==typeof e.components?e.components(o):e.components||o:i(e.components),n.createElement(s.Provider,{value:r},e.children)}}}]);